### ISSUE TITLE
fix imports for CRAN

### ISSUE THREAD

**Issue by jefferis** [jefferislab/nat.nblast#30]
We should submit a version to CRAN to accompany the paper. v 1.5 is coming up with errors on r-devel due to stricter namespace checking. These buglets still exsist.

https://www.r-project.org/nosvn/R.check/r-devel-osx-x86_64-clang/nat.nblast-00check.html

```
checking R code for possible problems ... NOTE
WeightedNNBasedLinesetDistFun : <anonymous>: no visible global function
  definition for ‘dnorm’
nhclust: no visible binding for global variable ‘as.dist’
nhclust: no visible global function definition for ‘hclust’
plot3d.hclust: no visible binding for global variable ‘rainbow’
show_similarity: no visible global function definition for
  ‘colorRampPalette’
sub_dist_mat: no visible global function definition for ‘as.dist’
Undefined global functions or variables:
  as.dist colorRampPalette dnorm hclust rainbow
Consider adding
  importFrom("grDevices", "colorRampPalette", "rainbow")
  importFrom("stats", "as.dist", "dnorm", "hclust")
to your NAMESPACE file.
```

**Comment by ajdm** [comment]
I think this is fixed as of f4d9eb2d016ab731b65836343e408c0acc73267b, but I'm having trouble installing all the packages to check on my machine with R-devel, as ``igraph`` and ``RcppEigen`` aren't happy on the Fortran front.

**Comment by jefferis** [comment]
Thanks @ajdm. I just triggered a winbuilder build (devtools::build_win) which should confirm. You'll get the email!

**Comment by jefferis** [comment]
@ajdm was winbuilder happy with latest build?

**Comment by ajdm** [comment]
Yes, but CRAN was not. I need to fix the VignetteIndex and then they should
be happy.

**Comment by jefferis** [comment]
Thanks! I actually have one minor enhancement to push later tonight. Best, Greg.

**Comment by ajdm** [comment]
On CRAN now.

**Comment by jefferis** [comment]
Brilliant! Thanks!
