### ISSUE TITLE
Include neuron list of superclusters and clusters from nblast online?

### ISSUE THREAD

**Issue by jennyl617** [jefferislab/nat.nblast#33]
I was wondering if you had a dataset listing all the neurons belonging to each cluster/supercluster from online in your nblast R package, or whether this information is only accessible on the website. Thanks very much!

**Comment by jefferis** [comment]
Thanks for your interest. You can access this information using the https://github.com/jefferis/flycircuit package. 
```r
library(flycircuit)
apres16k.p0=load_si_data('apres16k.p0.rds')
apdf=as.data.frame(apres16k.p0)
str(apdf)
```
You can take a look at the source code for the figures at http://flybrain.mrc-lmb.cam.ac.uk/si/nblast/www/paper/ and https://github.com/jefferislab/NBLAST_figures.
If you need more help, please contact us via https://groups.google.com/forum/embed/?place=forum/nat-user#!forum/nat-user.

**Comment by jennyl617** [comment]
Just a quick question: I noticed I get different flycircuit ids when I do the following:
`fc_idid(apdf$item[(apdf$cluster == 1)])`
versus
`apdf$idx[(apdf$cluster == 1)]`

Did I perhaps miss something? Looks like the ids for the first half of the list are correct, but begin to diverge afterward. Thanks so much for your help!

**Comment by jefferis** [comment]
The first form using `fcidid` is correct. The other id is not a flycircuit id but a sequential number generated in the clustering. In general I recommend referring to neurons using the character identifiers to avoid such ambiguities.
